---
# tasks file for webserver
- name: Copy Configuration Files
  copy:
    src: 'config_files/{{ item }}'
    dest: '/{{ item }}'
  with_items: '{{ apache_config_files }}'
  when: item not in apache_config_skip
