galaxy_info:
  author: your name
  description: your description
  company: your company (optional)

  license: license (GPLv2, CC-BY, etc)

  min_ansible_version: 1.2
  galaxy_tags: []

dependencies:
  - role: apache
    apache_config_skip: '{{ webmin_config_files }} + {{ webmin_config_skip }}'
    
