---
# tasks file for common_config
- name: Copy Configuration Files
  copy:
    src: 'config_files/{{ item }}'
    dest: '/{{ item }}'
    force: True
  when: item not in config_skip
  with_items: '{{ config_files }}'
