---
# tasks file for webserver
- name: Copy Configuration Files
  copy:
    src: 'config_files/{{ config_file }}'
    dest: '/{{ config_file }}'
  loop_control:
    loop_var: config_file
  with_items: '{{ config_files }}'

